language: node_js

cache:
    - npm
    - yarn

node_js:
    - "lts/*"
    - "node"

after_success:
    - yarn build
    - if [ -n "$TRAVIS_TAG" ]; then npm version $TRAVIS_TAG; fi

deploy:
    edge: true

    - provider: npm
      email: richiebendall@gmail.com
      cleanup: false
      api_key: $npm_token
      on:
          tags: true

    - provider: pages
      cleanup: false
      token: $github_token
      committer_from_gh: true
      keep_history: true
      local_dir: docs
      on:
          tags: true
